apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  namespace: default
spec:
  selector:
    app: netflix-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000  # Change this to match your pod's container port
  type: ClusterIP
